In [1]:
import pandas as pd

In [3]:
population_predict = pd.read_csv("Population_predicted_ML.csv")
population_predict = population_predict.loc[population_predict["Year"]>2010]
population_predict

          Country  Year  population_predicted
5     Afghanistan  2015                 29741
6     Afghanistan  2020                 31805
7     Afghanistan  2025                 33868
8     Afghanistan  2030                 35931
9     Afghanistan  2035                 37995
...           ...   ...                   ...
2959     Zimbabwe  2030                 17481
2960     Zimbabwe  2035                 18467
2961     Zimbabwe  2040                 19453
2962     Zimbabwe  2045                 20439
2963     Zimbabwe  2050                 21425

[1824 rows x 3 columns]

In [7]:
beg_pop = 0
pop_2015 = 0
population_predict["year change"] = 0
population_predict["running_total_change"] = 0
population_predict["percent_change"] = 0

for index, row in population_predict.iterrows():
    if row["Year"] == 2015:
        pop_2015 =  row["population_predicted"]
        population_predict.loc[index, 'year change'] = 0
        population_predict.loc[index, 'running_total_change'] = 0
        beg_pop = row["population_predicted"]
        running_total = 0
        population_predict.loc[index, 'percent_change'] = 0
    else:
        change = row["population_predicted"] - beg_pop
        running_total = running_total + change
        population_predict.loc[index, 'year change'] = change
        population_predict.loc[index, 'running_total_change'] = running_total
        beg_pop = row["population_predicted"]
        population_predict.loc[index, 'percent_change'] = running_total/pop_2015
        
population_predict.head(20)

,Country,Year,population_predicted,year change,running_total_change,percent_change
5,Afghanistan,2015,29741,0,0,0.000000
6,Afghanistan,2020,31805,2064,2064,0.069399
7,Afghanistan,2025,33868,2063,4127,0.138765
8,Afghanistan,2030,35931,2063,6190,0.208130
9,Afghanistan,2035,37995,2064,8254,0.277529
10,Afghanistan,2040,40058,2063,10317,0.346895
11,Afghanistan,2045,42122,2064,12381,0.416294
12,Afghanistan,2050,44185,2063,14444,0.485660
18,Albania,2015,3411,0,0,0.000000
19,Albania,2020,3541,130,130,0.038112
20,Albania,2025,3670,129,259,0.075931
21,Albania,2030,3800,130,389,0.114043
22,Albania,2035,3930,130,519,0.152155
23,Albania,2040,4060,130,649,0.190267
24,Albania,2045,4189,129,778,0.228086
25,Albania,2050,4319,130,908,0.266198
31,Algeria,2015,38987,0,0,0.000000
32,Algeria,2020,41720,2733,2733,0.070100
33,Algeria,2025,44453,2733,5466,0.140201
34,Algeria,2030,47186,2733,8199,0.210301

In [8]:
population_predict.to_csv("predicted_population_year_change.csv",index=False)